Co tracker
IERoboticsClub/PoW pull request #2
Opened 2023-09-13 18:44 UTC by velocitatem

Work in Progress ✔️

2023-09-14 08:19 UTC, velocitatem commented
We could run the notebook on the big screen at the lab? Since it integrates with the computer's camera, could be nice to see a semi-live demo.

2023-09-14 17:56 UTC, velocitatem commented
+ [ ] Add comments to the code - mapping the inputs from the paper

2023-09-14 17:58 UTC, velocitatem commented
https://viper.cs.columbia.edu/ Is the other model I mentioned at the end.

2023-09-26 10:22 UTC, dsanmart commented on cotracker/cotracker-simple-implementation.ipynb
Could you run the notebook and commit the outputs? This way everyone can take a quick look at them without having to do the whole setup.

2023-09-26 10:24 UTC, velocitatem commented on cotracker/cotracker-simple-implementation.ipynb
Sounds good! Will do 👍🏻

2023-09-26 10:30 UTC, dsanmart commented on cotracker/README.md
> +```mermaid
If you are going into how the architecture of Cotracker works. Perhaps also include figures 2 and 3 for better understanding.

2023-09-26 10:31 UTC, dsanmart requested changes
Great content! Thanks for the contribution @velocitatem and all the explanations in the README. I added some minor feedback

2023-09-26 11:34 UTC, vtwoptwo requested changes
Awesome! Looks great. Ping me when u make the small changes and other than that LGTM!

2023-09-26 11:34 UTC, vtwoptwo commented on Makefile
> +TOPIC ?= cotracker
here there is no need to add another default. I just added it in case someone runs the make command without setting a different TOPIC variable

2023-09-26 11:34 UTC, vtwoptwo commented on cotracker/README.md
> +
```suggestion
Example prompts:
```

2023-09-26 11:34 UTC, vtwoptwo commented on cotracker/README.md
> +A new state of the art architecture for optical flow and particle tracking proposed by meta. The key innovation in this project is the use of Transformer Architecture and the idea that tracking multi
```suggestion
A new state-of-the-art architecture for optical flow and particle tracking proposed by Meta. The key innovation in this project is the use of Transformer Architecture and the idea that tracking multiple particles concurrently, can help boos overall accuracy.
```

2023-09-26 11:34 UTC, vtwoptwo commented on cotracker/README.md
> +A new state of the art architecture for optical flow and particle tracking proposed by meta. The key innovation in this project is the use of Transformer Architecture and the idea that tracking multi
The key innovation in this project is the use of Transformer Architecture and the idea that tracking multiple particles concurrently, can help boos overall accuracy. -> This sentence is a bit weird maybe rephrase it...?

2023-09-26 11:34 UTC, vtwoptwo commented on cotracker/cotracker-simple-implementation.ipynb
> +    "    filename=output_filename, # name of file t\n",
```suggestion
    "    filename=output_filename, # name of output file\n",
```

2023-09-26 11:34 UTC, vtwoptwo commented on cotracker/cotracker-simple-implementation.ipynb
In general cool! Maybe comment each cell what each step is.

2023-09-26 11:34 UTC, vtwoptwo commented on cotracker/requirements.txt
versions for each dependency

2023-09-27 11:20 UTC, dsanmart commented
It seems like the png files for the figures have not been committed

2023-10-01 20:13 UTC, vtwoptwo reviewed
lgtm

2023-10-01 20:13 UTC, vtwoptwo approved these changes

2023-10-01 20:14 UTC, merged